import { GLTF } from "three-stdlib";
import { AnimationAction, AnimationClip, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from "three";



interface GLTFAction extends AnimationClip {
  name: ActionName;
}

//#region GltfTypes

export type GLTFResult = GLTF & {
  nodes: {
    Cube014: Mesh;
    PecasMetal: Mesh;
    PCPartes: Mesh;
    Leds: Mesh;
    SSD: Mesh;
    VidroPc: Mesh;
    Plane035: Mesh;
    Plane035_1: Mesh;
    Cube012: Mesh;
    Cube012_1: Mesh;
    Cube012_2: Mesh;
    Cube012_3: Mesh;
    Livro6: Mesh;
    BookStack4: Mesh;
    BookStack1: Mesh;
    MousePad: Mesh;
    MonitorBotao: Mesh;
    MonitorAtras1: Mesh;
    MonitorAtras2: Mesh;
    MonitorAtras3: Mesh;
    PeMonitor2: Mesh;
    PeMonitor3: Mesh;
    AcerHold: Mesh;
    MoldeTela: Mesh;
    KeyBoard: Mesh;
    Object_6004: Mesh;
    Object_6004_1: Mesh;
    Cylinder: Mesh;
    Cylinder_1: Mesh;
    Circle_0: Mesh;
    Circle_1: Mesh;
    Circle_2: Mesh;
    Circle_3: Mesh;
    Circle_4: Mesh;
    Cama: Mesh;
    MoldeTeclado: Mesh;
    CutoffSlider: Mesh;
    C3: Mesh;
    B2: Mesh;
    A2: Mesh;
    G2: Mesh;
    F2: Mesh;
    E2: Mesh;
    D2: Mesh;
    C2: Mesh;
    B1: Mesh;
    A1: Mesh;
    G1: Mesh;
    F1: Mesh;
    E1: Mesh;
    D1: Mesh;
    C1: Mesh;
    D3: Mesh;
    E3: Mesh;
    F3: Mesh;
    G3: Mesh;
    A3: Mesh;
    B3: Mesh;
    C4: Mesh;
    D4: Mesh;
    E4: Mesh;
    F4: Mesh;
    ["A#2"]: Mesh;
    ["G#2"]: Mesh;
    ["F#2"]: Mesh;
    ["D#2"]: Mesh;
    ["C#2"]: Mesh;
    ["A#1"]: Mesh;
    ["G#1"]: Mesh;
    ["F#1"]: Mesh;
    ["D#1"]: Mesh;
    ["C#1"]: Mesh;
    ["A#3"]: Mesh;
    ["C#3"]: Mesh;
    ["C#4"]: Mesh;
    ["D#3"]: Mesh;
    ["D#4"]: Mesh;
    ["F#3"]: Mesh;
    ["G#3"]: Mesh;
    Prateleira: Mesh;
    BookBack: Mesh;
    Plane029: Mesh;
    Plane029_1: Mesh;
    Cube007: Mesh;
    Cube007_1: Mesh;
    Cube007_2: Mesh;
    Page1: Mesh;
    Page2: Mesh;
    Page3: Mesh;
    Page4: Mesh;
    Page8: Mesh;
    Page7: Mesh;
    Page6: Mesh;
    Page5: Mesh;
    Page13: Mesh;
    Page14: Mesh;
    Page15: Mesh;
    Page16: Mesh;
    Page12: Mesh;
    Page11: Mesh;
    Page10: Mesh;
    Page9: Mesh;
    Page25: Mesh;
    Page26: Mesh;
    Page27: Mesh;
    Page28: Mesh;
    Page32: Mesh;
    Page31: Mesh;
    Page30: Mesh;
    Page29: Mesh;
    Page21: Mesh;
    Page22: Mesh;
    Page23: Mesh;
    Page24: Mesh;
    Page20: Mesh;
    Page19: Mesh;
    Page18: Mesh;
    Page17: Mesh;
    Page49LastFlip: Mesh;
    Page56: Mesh;
    Page55: Mesh;
    Page61: Mesh;
    Page62: Mesh;
    Page63: Mesh;
    Page64: Mesh;
    Page60: Mesh;
    Page59: Mesh;
    Page58: Mesh;
    Page57: Mesh;
    Page41: Mesh;
    Page42: Mesh;
    Page43: Mesh;
    Page44: Mesh;
    Page48: Mesh;
    Page47: Mesh;
    Page46: Mesh;
    Page45: Mesh;
    Page37: Mesh;
    Page38: Mesh;
    Page39: Mesh;
    Page40: Mesh;
    Page36: Mesh;
    Page35: Mesh;
    Page34: Mesh;
    Page33: Mesh;
    Page65: Mesh;
    Page66: Mesh;
    Page67: Mesh;
    Page68: Mesh;
    Page72: Mesh;
    Page71: Mesh;
    Page70: Mesh;
    Page69: Mesh;
    Page77: Mesh;
    Page78: Mesh;
    Page79: Mesh;
    Page80: Mesh;
    Page76: Mesh;
    Page75: Mesh;
    Page74: Mesh;
    Page73: Mesh;
    Page89: Mesh;
    Page90: Mesh;
    Page91: Mesh;
    Page92: Mesh;
    Page96: Mesh;
    Page95: Mesh;
    Page94: Mesh;
    Page93: Mesh;
    Page85: Mesh;
    Page86: Mesh;
    Page87: Mesh;
    Page88: Mesh;
    Page84: Mesh;
    Page83: Mesh;
    Page82: Mesh;
    Page81: Mesh;
    Page99: Mesh;
    Page98: Mesh;
    Page97: Mesh;
    Page50: Mesh;
    Page51: Mesh;
    Page52: Mesh;
    Page53: Mesh;
    Page54: Mesh;
    Mesh019: Mesh;
    Mesh019_1: Mesh;
    ["Wood_W-L"]: Mesh;
    ["Wood_W-R"]: Mesh;
    DetalheVitrola: Mesh;
    TampaVitrola: Mesh;
    Operating_glass_L: Mesh;
  };
  materials: {
    PaletteMaterial001: MeshStandardMaterial;
    // PaletteMaterial001: LineBasicMaterial
    PaletteMaterial002: MeshStandardMaterial;
    aiStandardSurface14SG: MeshStandardMaterial;
    PaletteMaterial003: MeshStandardMaterial;
    aiStandardSurface9SG: MeshStandardMaterial;
    PaletteMaterial004: MeshStandardMaterial;
    ["LED Stripe"]: MeshStandardMaterial;
    PaletteMaterial005: MeshPhysicalMaterial;
    LeftWallMaterial: MeshStandardMaterial;
    MiddleWallMaterial: MeshStandardMaterial;
    RightWallMaterial: MeshStandardMaterial;
    FloorMaterial: MeshStandardMaterial;
    Books: MeshStandardMaterial;
    PropBooksMaterial2: MeshStandardMaterial;
    PropBookMaterial: MeshStandardMaterial;
    MousePadMaterial: MeshStandardMaterial;
    BotoesMonitorImg: MeshStandardMaterial;
    BackMonitorMaterial: MeshStandardMaterial;
    ["achter.ribbel.001"]: MeshStandardMaterial;
    ["logo.coutout.smooth.001"]: MeshStandardMaterial;
    ["logo.coutout.smooth"]: MeshStandardMaterial;
    PeMonitorMaterial2: MeshStandardMaterial;
    AcerLoogo: MeshStandardMaterial;
    VoltaMonitorMaterial: MeshStandardMaterial;
    TecladoMaterial: MeshStandardMaterial;
    centerVitrola: MeshStandardMaterial;
    Indoor_Plant_pot: MeshStandardMaterial;
    FlorMaterial: MeshStandardMaterial;
    Indoor_Plant: MeshStandardMaterial;
    Indoor_Plant_ground: MeshStandardMaterial;
    BedMaterial: MeshStandardMaterial;
    PaletteMaterial007: MeshStandardMaterial;
    PaletteMaterial008: MeshStandardMaterial;
    PaletteMaterial009: MeshStandardMaterial;
    BookCover: MeshStandardMaterial;
    PaletteMaterial010: MeshStandardMaterial;
    MoldeVidroMaterial: MeshStandardMaterial;
    PaletteMaterial012: MeshStandardMaterial;
    vitrolaWood: MeshStandardMaterial;
    PaletteMaterial006: MeshStandardMaterial;
    PaletteMaterial011: MeshPhysicalMaterial;
  };
  animations: GLTFAction[];
};

export type ActionName =
  | "AgulhaFirstTrackAction"
  | "AgulhaFirstTrackActionToFinish"
  | "AgulhaFourthToEndAction"
  | "AgulhaFourthTrackAction"
  | "AgulhaSecondTrackAction"
  | "AgulhaThirdTrackAction"
  | "DiscAction"
  | "C3PressAction"
  | "B2PressAction"
  | "A2PressAction"
  | "G2PressAction"
  | "F2PressAction"
  | "E2PressAction"
  | "D2PressAction"
  | "C2PressAction"
  | "B1PressAction"
  | "A1PressAction"
  | "G1PressAction"
  | "F1PressAction"
  | "E1PressAction"
  | "D1PressAction"
  | "C1PressAction"
  | "D3PressAction"
  | "E3PressAction"
  | "F3PressAction"
  | "G3PressAction"
  | "A3PressAction"
  | "B3PressAction"
  | "C4PressAction"
  | "D4PressAction"
  | "E4PressAction"
  | "F4PressAction"
  | "A#2PressAction"
  | "G#2PressAction"
  | "F#2PressAction"
  | "D#2PressAction"
  | "C#2PressAction"
  | "A#1PressAction"
  | "G#1PressAction"
  | "F#1PressAction"
  | "D#1PressAction"
  | "C#1Press"
  | "A#3PressAction"
  | "C#3PressAction"
  | "C#4PressAction"
  | "D#3PressAction"
  | "D#4PressAction"
  | "F#3PressAction"
  | "G#3PressAction"
  | "BookFace"
  | "BookSide"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "SplitPagesAction"
  | "RotacaoFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "OpeningPageRightMove"
  | "RotacaoRightFirstMove"
  | "FlipPage1"
  | "AjustePageOpening"
  | "RotacaoPageOneToLeft"
  | "RotacaoPageOneRight"
  | "FlipPage2"
  | "Page2AdjustmentOpen"
  | "Page2Rotation"
  | "Page2RotacaoAdjustment"
  | "FlipPage3"
  | "AjusteOpeningPage4"
  | "Page3Rotacao"
  | "RotacaoAjusteOpen"
  | "FlipPage4"
  | "RotacaoPagina4"
  | "OpeningRotacaoPage4"
  | "FlipPage5"
  | "AjusteOpeningPage5"
  | "RotacaoP5"
  | "RotacaoFirstMovePage5"
  | "RightWindowAction"
  | "TesteBrincadeira"
  | "LeftWindowTrack";

  
type GLTFActions = Record<ActionName, AnimationAction>;
