import type { NextPage } from "next";
import { motion, useScroll, useTransform, useSpring, useMotionValueEvent } from "framer-motion";
import { useEffect, useState, useRef } from "react";

const Home: NextPage = () => {
  const divProp = useRef(null);
  const refRodrigo = useRef(null);
  const refCariello = useRef(null);

  
  const [stateRodrigo, setStateRodrigo] = useState("RODRIGO");
  const [stateCariello, setStateCariello] = useState("CARIELLO");

  const { scrollYProgress } = useScroll();

  const [hookedYPostion, setHookedYPosition] = useState(0);
  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    setHookedYPosition(latest);
  })

  console.log(hookedYPostion);
  const progress = useSpring(hookedYPostion,{mass: 0.1});
  const widthTeste = useTransform(progress, [0,1], ["100%", "0%"])

  useEffect(() => {
    if(hookedYPostion > 1){
        setStateRodrigo("abuabuaaa")
    }

  },[hookedYPostion])

 

  const [loading, setLoading] = useState(true);
  useEffect(() => {
    
    const timer = setTimeout(() => {
      setLoading(false);
    }, 5300);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="font-rubick relative flex h-screen flex-col bg-dark-mode pt-24">
      <motion.div className="flex" ref={divProp} style={{width: widthTeste}}>
        <motion.h1
          ref={refRodrigo}
          style={{ color: "white", fontSize: "220px", fontStyle: "italic" }}
        >
          {stateRodrigo}
        </motion.h1>
        <motion.h1
          ref={refCariello}
          style={{ color: "white", fontSize: "220px", fontStyle: "italic" }}
        >
          {stateCariello}
        </motion.h1>
      </motion.div>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>

      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>
      <><h1>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</h1></>

    </div>
  );
};

export default Home;
