/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useBounds } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useThree } from "@react-three/fiber";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    PecasMetal: THREE.Mesh
    PCPartes: THREE.Mesh
    Leds: THREE.Mesh
    SSD: THREE.Mesh
    VidroPc: THREE.Mesh
    Plane035: THREE.Mesh
    Plane035_1: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube012_2: THREE.Mesh
    Cube012_3: THREE.Mesh
    Livro6: THREE.Mesh
    BookStack4: THREE.Mesh
    BookStack1: THREE.Mesh
    MousePad: THREE.Mesh
    MonitorBotao: THREE.Mesh
    MonitorAtras1: THREE.Mesh
    MonitorAtras2: THREE.Mesh
    MonitorAtras3: THREE.Mesh
    PeMonitor2: THREE.Mesh
    PeMonitor3: THREE.Mesh
    AcerHold: THREE.Mesh
    MoldeTela: THREE.Mesh
    KeyBoard: THREE.Mesh
    Object_6004: THREE.Mesh
    Object_6004_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Circle_0: THREE.Mesh
    Circle_1: THREE.Mesh
    Circle_2: THREE.Mesh
    Circle_3: THREE.Mesh
    Circle_4: THREE.Mesh
    Cama: THREE.Mesh
    MoldeTeclado: THREE.Mesh
    CutoffSlider: THREE.Mesh
    C3: THREE.Mesh
    B2: THREE.Mesh
    A2: THREE.Mesh
    G2: THREE.Mesh
    F2: THREE.Mesh
    E2: THREE.Mesh
    D2: THREE.Mesh
    C2: THREE.Mesh
    B1: THREE.Mesh
    A1: THREE.Mesh
    G1: THREE.Mesh
    F1: THREE.Mesh
    E1: THREE.Mesh
    D1: THREE.Mesh
    C1: THREE.Mesh
    D3: THREE.Mesh
    E3: THREE.Mesh
    F3: THREE.Mesh
    G3: THREE.Mesh
    A3: THREE.Mesh
    B3: THREE.Mesh
    C4: THREE.Mesh
    D4: THREE.Mesh
    E4: THREE.Mesh
    F4: THREE.Mesh
    ['A#2']: THREE.Mesh
    ['G#2']: THREE.Mesh
    ['F#2']: THREE.Mesh
    ['D#2']: THREE.Mesh
    ['C#2']: THREE.Mesh
    ['A#1']: THREE.Mesh
    ['G#1']: THREE.Mesh
    ['F#1']: THREE.Mesh
    ['D#1']: THREE.Mesh
    ['C#1']: THREE.Mesh
    ['A#3']: THREE.Mesh
    ['C#3']: THREE.Mesh
    ['C#4']: THREE.Mesh
    ['D#3']: THREE.Mesh
    ['D#4']: THREE.Mesh
    ['F#3']: THREE.Mesh
    ['G#3']: THREE.Mesh
    Prateleira: THREE.Mesh
    BookBack: THREE.Mesh
    Plane029: THREE.Mesh
    Plane029_1: THREE.Mesh
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
    Cube007_2: THREE.Mesh
    Page1: THREE.Mesh
    Page2: THREE.Mesh
    Page3: THREE.Mesh
    Page4: THREE.Mesh
    Page8: THREE.Mesh
    Page7: THREE.Mesh
    Page6: THREE.Mesh
    Page5: THREE.Mesh
    Page13: THREE.Mesh
    Page14: THREE.Mesh
    Page15: THREE.Mesh
    Page16: THREE.Mesh
    Page12: THREE.Mesh
    Page11: THREE.Mesh
    Page10: THREE.Mesh
    Page9: THREE.Mesh
    Page25: THREE.Mesh
    Page26: THREE.Mesh
    Page27: THREE.Mesh
    Page28: THREE.Mesh
    Page32: THREE.Mesh
    Page31: THREE.Mesh
    Page30: THREE.Mesh
    Page29: THREE.Mesh
    Page21: THREE.Mesh
    Page22: THREE.Mesh
    Page23: THREE.Mesh
    Page24: THREE.Mesh
    Page20: THREE.Mesh
    Page19: THREE.Mesh
    Page18: THREE.Mesh
    Page17: THREE.Mesh
    Page49LastFlip: THREE.Mesh
    Page56: THREE.Mesh
    Page55: THREE.Mesh
    Page61: THREE.Mesh
    Page62: THREE.Mesh
    Page63: THREE.Mesh
    Page64: THREE.Mesh
    Page60: THREE.Mesh
    Page59: THREE.Mesh
    Page58: THREE.Mesh
    Page57: THREE.Mesh
    Page41: THREE.Mesh
    Page42: THREE.Mesh
    Page43: THREE.Mesh
    Page44: THREE.Mesh
    Page48: THREE.Mesh
    Page47: THREE.Mesh
    Page46: THREE.Mesh
    Page45: THREE.Mesh
    Page37: THREE.Mesh
    Page38: THREE.Mesh
    Page39: THREE.Mesh
    Page40: THREE.Mesh
    Page36: THREE.Mesh
    Page35: THREE.Mesh
    Page34: THREE.Mesh
    Page33: THREE.Mesh
    Page65: THREE.Mesh
    Page66: THREE.Mesh
    Page67: THREE.Mesh
    Page68: THREE.Mesh
    Page72: THREE.Mesh
    Page71: THREE.Mesh
    Page70: THREE.Mesh
    Page69: THREE.Mesh
    Page77: THREE.Mesh
    Page78: THREE.Mesh
    Page79: THREE.Mesh
    Page80: THREE.Mesh
    Page76: THREE.Mesh
    Page75: THREE.Mesh
    Page74: THREE.Mesh
    Page73: THREE.Mesh
    Page89: THREE.Mesh
    Page90: THREE.Mesh
    Page91: THREE.Mesh
    Page92: THREE.Mesh
    Page96: THREE.Mesh
    Page95: THREE.Mesh
    Page94: THREE.Mesh
    Page93: THREE.Mesh
    Page85: THREE.Mesh
    Page86: THREE.Mesh
    Page87: THREE.Mesh
    Page88: THREE.Mesh
    Page84: THREE.Mesh
    Page83: THREE.Mesh
    Page82: THREE.Mesh
    Page81: THREE.Mesh
    Page99: THREE.Mesh
    Page98: THREE.Mesh
    Page97: THREE.Mesh
    Page50: THREE.Mesh
    Page51: THREE.Mesh
    Page52: THREE.Mesh
    Page53: THREE.Mesh
    Page54: THREE.Mesh
    Mesh019: THREE.Mesh
    Mesh019_1: THREE.Mesh
    ['Wood_W-L']: THREE.Mesh
    ['Wood_W-R']: THREE.Mesh
    DetalheVitrola: THREE.Mesh
    TampaVitrola: THREE.Mesh
    Operating_glass_L: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    // PaletteMaterial001: THREE.LineBasicMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    aiStandardSurface14SG: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    aiStandardSurface9SG: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    ['LED Stripe']: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    LeftWallMaterial: THREE.MeshStandardMaterial
    MiddleWallMaterial: THREE.MeshStandardMaterial
    RightWallMaterial: THREE.MeshStandardMaterial
    FloorMaterial: THREE.MeshStandardMaterial
    Books: THREE.MeshStandardMaterial
    PropBooksMaterial2: THREE.MeshStandardMaterial
    PropBookMaterial: THREE.MeshStandardMaterial
    MousePadMaterial: THREE.MeshStandardMaterial
    BotoesMonitorImg: THREE.MeshStandardMaterial
    BackMonitorMaterial: THREE.MeshStandardMaterial
    ['achter.ribbel.001']: THREE.MeshStandardMaterial
    ['logo.coutout.smooth.001']: THREE.MeshStandardMaterial
    ['logo.coutout.smooth']: THREE.MeshStandardMaterial
    PeMonitorMaterial2: THREE.MeshStandardMaterial
    AcerLoogo: THREE.MeshStandardMaterial
    VoltaMonitorMaterial: THREE.MeshStandardMaterial
    TecladoMaterial: THREE.MeshStandardMaterial
    centerVitrola: THREE.MeshStandardMaterial
    Indoor_Plant_pot: THREE.MeshStandardMaterial
    FlorMaterial: THREE.MeshStandardMaterial
    Indoor_Plant: THREE.MeshStandardMaterial
    Indoor_Plant_ground: THREE.MeshStandardMaterial
    BedMaterial: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    BookCover: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    MoldeVidroMaterial: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshStandardMaterial
    vitrolaWood: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshPhysicalMaterial
  },
  animations: GLTFAction[];
}

type ActionName =
  | 'AgulhaFirstTrackAction'
  | 'AgulhaFirstTrackActionToFinish'
  | 'AgulhaFourthToEndAction'
  | 'AgulhaFourthTrackAction'
  | 'AgulhaSecondTrackAction'
  | 'AgulhaThirdTrackAction'
  | 'DiscAction'
  | 'C3PressAction'
  | 'B2PressAction'
  | 'A2PressAction'
  | 'G2PressAction'
  | 'F2PressAction'
  | 'E2PressAction'
  | 'D2PressAction'
  | 'C2PressAction'
  | 'B1PressAction'
  | 'A1PressAction'
  | 'G1PressAction'
  | 'F1PressAction'
  | 'E1PressAction'
  | 'D1PressAction'
  | 'C1PressAction'
  | 'D3PressAction'
  | 'E3PressAction'
  | 'F3PressAction'
  | 'G3PressAction'
  | 'A3PressAction'
  | 'B3PressAction'
  | 'C4PressAction'
  | 'D4PressAction'
  | 'E4PressAction'
  | 'F4PressAction'
  | 'A#2PressAction'
  | 'G#2PressAction'
  | 'F#2PressAction'
  | 'D#2PressAction'
  | 'C#2PressAction'
  | 'A#1PressAction'
  | 'G#1PressAction'
  | 'F#1PressAction'
  | 'D#1PressAction'
  | 'C#1Press'
  | 'A#3PressAction'
  | 'C#3PressAction'
  | 'C#4PressAction'
  | 'D#3PressAction'
  | 'D#4PressAction'
  | 'F#3PressAction'
  | 'G#3PressAction'
  | 'BookFace'
  | 'BookSide'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'SplitPagesAction'
  | 'RotacaoFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'OpeningPageRightMove'
  | 'RotacaoRightFirstMove'
  | 'FlipPage1'
  | 'AjustePageOpening'
  | 'RotacaoPageOneToLeft'
  | 'RotacaoPageOneRight'
  | 'FlipPage2'
  | 'Page2AdjustmentOpen'
  | 'Page2Rotation'
  | 'Page2RotacaoAdjustment'
  | 'FlipPage3'
  | 'AjusteOpeningPage4'
  | 'Page3Rotacao'
  | 'RotacaoAjusteOpen'
  | 'FlipPage4'
  | 'RotacaoPagina4'
  | 'OpeningRotacaoPage4'
  | 'FlipPage5'
  | 'AjusteOpeningPage5'
  | 'RotacaoP5'
  | 'RotacaoFirstMovePage5'
  | 'RightWindowAction'
  | 'TesteBrincadeira'
  | 'LeftWindowTrack'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Cena(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/cena-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  const { camera } = useThree(); 
 
  // useEffect(() => {
  //   if (nodes.Cama) {
  //     camera.lookAt(nodes.Cama.position);
  //   }

  // },[camera, nodes.Cama])
  
 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mesa" position={[-22.853, 7.13, 17.035]}>
          <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry}>
            <meshLambertMaterial attach="material" color="#fdf5e6"/>
          </mesh>
          
        </group>
        <mesh name="PecasMetal" castShadow receiveShadow geometry={nodes.PecasMetal.geometry} material={materials.PaletteMaterial002} position={[-25.144, 9.748, 9.324]} rotation={[-Math.PI, -0.635, Math.PI / 2]} scale={[0.415, 0.508, 0.552]} />
        <mesh name="PCPartes" castShadow receiveShadow geometry={nodes.PCPartes.geometry} material={materials.aiStandardSurface14SG} position={[-25.144, 9.748, 9.324]} rotation={[-Math.PI, -0.635, Math.PI / 2]} scale={[0.415, 0.508, 0.552]} />
        <mesh name="Leds" castShadow receiveShadow geometry={nodes.Leds.geometry} material={materials.PaletteMaterial003} position={[-25.144, 9.748, 9.324]} rotation={[-Math.PI, -0.635, Math.PI / 2]} scale={[0.415, 0.508, 0.552]} />
        <mesh name="SSD" castShadow receiveShadow geometry={nodes.SSD.geometry} material={materials.aiStandardSurface9SG} position={[-25.144, 9.748, 9.324]} rotation={[-Math.PI, -0.635, Math.PI / 2]} scale={[0.415, 0.508, 0.552]} />
        <mesh name="VidroPc" castShadow receiveShadow geometry={nodes.VidroPc.geometry} material={materials.PaletteMaterial004} position={[-25.144, 9.748, 9.324]} rotation={[-Math.PI, -0.635, Math.PI / 2]} scale={[0.415, 0.508, 0.552]} />
        <group name="LED_Streifen020" position={[-23.422, 19.103, 23.274]}>
          <mesh name="Plane035" castShadow receiveShadow geometry={nodes.Plane035.geometry} material={materials['LED Stripe']} />
          <mesh name="Plane035_1" castShadow receiveShadow geometry={nodes.Plane035_1.geometry} material={materials.PaletteMaterial005} />
        </group>
        <group name="Wall" position={[-8.761, 15.37, 1.697]}>
          <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials.LeftWallMaterial} />
          <mesh name="Cube012_1" castShadow receiveShadow geometry={nodes.Cube012_1.geometry} material={materials.MiddleWallMaterial} />
          <mesh name="Cube012_2" castShadow receiveShadow geometry={nodes.Cube012_2.geometry} material={materials.RightWallMaterial} />
          <mesh name="Cube012_3" castShadow receiveShadow geometry={nodes.Cube012_3.geometry} material={materials.FloorMaterial} />
        </group>
        <mesh name="Livro6" castShadow receiveShadow geometry={nodes.Livro6.geometry} material={materials.Books} position={[-9.473, 20.583, 26.927]} />
        <mesh name="BookStack4" castShadow receiveShadow geometry={nodes.BookStack4.geometry} material={materials.PropBooksMaterial2} position={[-26.728, 21.03, 18.123]} />
        <mesh name="BookStack1" castShadow receiveShadow geometry={nodes.BookStack1.geometry} material={materials.PropBookMaterial} position={[-26.755, 20.674, 12.341]} />
        <mesh name="MousePad" castShadow receiveShadow geometry={nodes.MousePad.geometry} material={materials.MousePadMaterial} position={[-25.798, 9.025, 17.987]} />
        <mesh name="MonitorBotao" castShadow receiveShadow geometry={nodes.MonitorBotao.geometry} material={materials.BotoesMonitorImg} position={[-26.967, 10.242, 16.06]} />
        <mesh name="MonitorAtras1" castShadow receiveShadow geometry={nodes.MonitorAtras1.geometry} material={materials.BackMonitorMaterial} position={[-27.106, 11.156, 17.987]} />
        <mesh name="MonitorAtras2" castShadow receiveShadow geometry={nodes.MonitorAtras2.geometry} material={materials['achter.ribbel.001']} position={[-26.995, 11.665, 18.021]} />
        <mesh name="MonitorAtras3" castShadow receiveShadow geometry={nodes.MonitorAtras3.geometry} material={materials['logo.coutout.smooth.001']} position={[-27.186, 11.025, 18.049]} />
        <mesh name="PeMonitor2" castShadow receiveShadow geometry={nodes.PeMonitor2.geometry} material={materials['logo.coutout.smooth']} position={[-27.176, 9.103, 18.012]} />
        <mesh name="PeMonitor3" castShadow receiveShadow geometry={nodes.PeMonitor3.geometry} material={materials.PeMonitorMaterial2} position={[-27.368, 9.126, 17.994]} />
        <mesh name="AcerHold" castShadow receiveShadow geometry={nodes.AcerHold.geometry} material={materials.AcerLoogo} position={[-26.846, 9.713, 18.007]} />
        <mesh name="MoldeTela" castShadow receiveShadow geometry={nodes.MoldeTela.geometry} material={materials.VoltaMonitorMaterial} position={[-26.901, 11.097, 17.998]} />
        <mesh name="KeyBoard" castShadow receiveShadow geometry={nodes.KeyBoard.geometry} material={materials.TecladoMaterial} position={[-25.453, 9.2, 19.918]} />
        <group name="AgulhaHolderVitrola" position={[-26.457, 9.45, 25.346]} rotation={[0.081, -0.812, 0.023]}>
          <mesh name="Object_6004" castShadow receiveShadow geometry={nodes.Object_6004.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Object_6004_1" castShadow receiveShadow geometry={nodes.Object_6004_1.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="Disc" position={[-26.031, 9.362, 25.874]} scale={[1.025, 0.003, 1.025]}>
          <mesh name="Cylinder" castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Cylinder_1" castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials.centerVitrola} />
        </group>
        <mesh name="Circle_0" castShadow receiveShadow geometry={nodes.Circle_0.geometry} material={materials.Indoor_Plant_pot} position={[-18.768, 9.353, 26.54]} />
        <mesh name="Circle_1" castShadow receiveShadow geometry={nodes.Circle_1.geometry} material={nodes.Circle_1.material} position={[-18.759, 9.013, 26.546]} />
        <mesh name="Circle_2" castShadow receiveShadow geometry={nodes.Circle_2.geometry} material={materials.FlorMaterial} position={[-18.757, 10.821, 26.528]} />
        <mesh name="Circle_3" castShadow receiveShadow geometry={nodes.Circle_3.geometry} material={materials.Indoor_Plant} position={[-18.783, 10.388, 26.465]} />
        <mesh name="Circle_4" castShadow receiveShadow geometry={nodes.Circle_4.geometry} material={materials.Indoor_Plant_ground} position={[-18.759, 9.683, 26.546]} />
        <mesh name="Cama" castShadow receiveShadow geometry={nodes.Cama.geometry} material={materials.BedMaterial} position={[-17.996, 6.461, -14.08]} />
        <mesh name="MoldeTeclado" castShadow receiveShadow geometry={nodes.MoldeTeclado.geometry} material={materials.PaletteMaterial007} position={[-16.274, 9.157, 9.032]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.019, 0.034]} />
        <mesh name="CutoffSlider" castShadow receiveShadow geometry={nodes.CutoffSlider.geometry} material={materials.PaletteMaterial008} position={[-17.093, 9.301, 9.159]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="C3" castShadow receiveShadow geometry={nodes.C3.geometry} material={materials.PaletteMaterial008} position={[-17.281, 9.196, 10.156]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="B2" castShadow receiveShadow geometry={nodes.B2.geometry} material={materials.PaletteMaterial008} position={[-17.518, 9.196, 10.155]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="A2" castShadow receiveShadow geometry={nodes.A2.geometry} material={materials.PaletteMaterial008} position={[-17.755, 9.196, 10.156]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="G2" castShadow receiveShadow geometry={nodes.G2.geometry} material={materials.PaletteMaterial008} position={[-17.998, 9.196, 10.159]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="F2" castShadow receiveShadow geometry={nodes.F2.geometry} material={materials.PaletteMaterial008} position={[-18.237, 9.196, 10.166]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="E2" castShadow receiveShadow geometry={nodes.E2.geometry} material={materials.PaletteMaterial008} position={[-18.481, 9.196, 10.171]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="D2" castShadow receiveShadow geometry={nodes.D2.geometry} material={materials.PaletteMaterial008} position={[-18.728, 9.196, 10.182]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="C2" castShadow receiveShadow geometry={nodes.C2.geometry} material={materials.PaletteMaterial008} position={[-18.976, 9.196, 10.186]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="B1" castShadow receiveShadow geometry={nodes.B1.geometry} material={materials.PaletteMaterial008} position={[-19.214, 9.196, 10.187]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="A1" castShadow receiveShadow geometry={nodes.A1.geometry} material={materials.PaletteMaterial008} position={[-19.45, 9.196, 10.197]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="G1" castShadow receiveShadow geometry={nodes.G1.geometry} material={materials.PaletteMaterial008} position={[-19.688, 9.196, 10.194]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="F1" castShadow receiveShadow geometry={nodes.F1.geometry} material={materials.PaletteMaterial008} position={[-19.931, 9.196, 10.207]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="E1" castShadow receiveShadow geometry={nodes.E1.geometry} material={materials.PaletteMaterial008} position={[-20.17, 9.206, 10.219]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="D1" castShadow receiveShadow geometry={nodes.D1.geometry} material={materials.PaletteMaterial008} position={[-20.421, 9.196, 10.226]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="C1" castShadow receiveShadow geometry={nodes.C1.geometry} material={materials.PaletteMaterial008} position={[-20.661, 9.206, 10.235]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="D3" castShadow receiveShadow geometry={nodes.D3.geometry} material={materials.PaletteMaterial008} position={[-17.04, 9.196, 10.158]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="E3" castShadow receiveShadow geometry={nodes.E3.geometry} material={materials.PaletteMaterial008} position={[-16.793, 9.196, 10.153]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="F3" castShadow receiveShadow geometry={nodes.F3.geometry} material={materials.PaletteMaterial008} position={[-16.549, 9.196, 10.148]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="G3" castShadow receiveShadow geometry={nodes.G3.geometry} material={materials.PaletteMaterial008} position={[-16.31, 9.196, 10.143]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="A3" castShadow receiveShadow geometry={nodes.A3.geometry} material={materials.PaletteMaterial008} position={[-16.067, 9.196, 10.146]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="B3" castShadow receiveShadow geometry={nodes.B3.geometry} material={materials.PaletteMaterial008} position={[-15.83, 9.196, 10.141]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="C4" castShadow receiveShadow geometry={nodes.C4.geometry} material={materials.PaletteMaterial008} position={[-15.593, 9.196, 10.136]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="D4" castShadow receiveShadow geometry={nodes.D4.geometry} material={materials.PaletteMaterial008} position={[-15.352, 9.196, 10.125]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="E4" castShadow receiveShadow geometry={nodes.E4.geometry} material={materials.PaletteMaterial008} position={[-15.105, 9.196, 10.12]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="F4" castShadow receiveShadow geometry={nodes.F4.geometry} material={materials.PaletteMaterial008} position={[-14.861, 9.196, 10.115]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={0.019} />
        <mesh name="A#2" castShadow receiveShadow geometry={nodes['A#2'].geometry} material={materials.PaletteMaterial008} position={[-17.653, 9.254, 9.968]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="G#2" castShadow receiveShadow geometry={nodes['G#2'].geometry} material={materials.PaletteMaterial008} position={[-17.881, 9.254, 9.98]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="F#2" castShadow receiveShadow geometry={nodes['F#2'].geometry} material={materials.PaletteMaterial008} position={[-18.125, 9.254, 9.982]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="D#2" castShadow receiveShadow geometry={nodes['D#2'].geometry} material={materials.PaletteMaterial008} position={[-18.604, 9.254, 9.997]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="C#2" castShadow receiveShadow geometry={nodes['C#2'].geometry} material={materials.PaletteMaterial008} position={[-18.847, 9.254, 10.007]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="A#1" castShadow receiveShadow geometry={nodes['A#1'].geometry} material={materials.PaletteMaterial008} position={[-19.336, 9.254, 10.007]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="G#1" castShadow receiveShadow geometry={nodes['G#1'].geometry} material={materials.PaletteMaterial008} position={[-19.565, 9.254, 10.009]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="F#1" castShadow receiveShadow geometry={nodes['F#1'].geometry} material={materials.PaletteMaterial008} position={[-19.809, 9.254, 10.02]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="D#1" castShadow receiveShadow geometry={nodes['D#1'].geometry} material={materials.PaletteMaterial008} position={[-20.294, 9.254, 10.043]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="C#1" castShadow receiveShadow geometry={nodes['C#1'].geometry} material={materials.PaletteMaterial008} position={[-20.537, 9.254, 10.047]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="A#3" castShadow receiveShadow geometry={nodes['A#3'].geometry} material={materials.PaletteMaterial008} position={[-15.965, 9.254, 9.967]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="C#3" castShadow receiveShadow geometry={nodes['C#3'].geometry} material={materials.PaletteMaterial008} position={[-17.16, 9.254, 9.971]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="C#4" castShadow receiveShadow geometry={nodes['C#4'].geometry} material={materials.PaletteMaterial008} position={[-15.471, 9.254, 9.939]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="D#3" castShadow receiveShadow geometry={nodes['D#3'].geometry} material={materials.PaletteMaterial008} position={[-16.916, 9.254, 9.979]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="D#4" castShadow receiveShadow geometry={nodes['D#4'].geometry} material={materials.PaletteMaterial008} position={[-15.228, 9.254, 9.934]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="F#3" castShadow receiveShadow geometry={nodes['F#3'].geometry} material={materials.PaletteMaterial008} position={[-16.437, 9.254, 9.969]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="G#3" castShadow receiveShadow geometry={nodes['G#3'].geometry} material={materials.PaletteMaterial008} position={[-16.193, 9.254, 9.964]} rotation={[-Math.PI, 1.55, -Math.PI]} scale={[0.019, 0.011, 0.019]} />
        <mesh name="Prateleira" castShadow receiveShadow geometry={nodes.Prateleira.geometry} material={materials.PaletteMaterial009} position={[-17.846, 19.526, 27.014]} scale={[1, 0.143, 1]} />
        <mesh name="BookBack" castShadow receiveShadow geometry={nodes.BookBack.geometry} material={materials.BookCover} position={[-20.042, 9.036, 24.868]} rotation={[-0.006, 0.006, 3.129]} scale={[0.342, 0.427, 0.427]} />
        <group name="BookFace" position={[-20.081, 9.27, 24.949]} rotation={[3.135, -0.006, -3.129]} scale={[0.342, 0.427, 0.427]}>
          <mesh name="Plane029" castShadow receiveShadow geometry={nodes.Plane029.geometry} material={materials.BookCover} />
          <mesh name="Plane029_1" castShadow receiveShadow geometry={nodes.Plane029_1.geometry} material={materials.BookCover} />
        </group>
        <group name="BookSIde" position={[-20.073, 9.028, 25.31]} rotation={[2.203, 1.555, -0.638]} scale={[0.427, 0.427, 0.342]}>
          <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.BookCover} />
          <mesh name="Cube007_1" castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Cube007_2" castShadow receiveShadow geometry={nodes.Cube007_2.geometry} material={materials.PaletteMaterial010} />
        </group>
        <mesh name="Page1" castShadow receiveShadow geometry={nodes.Page1.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.244, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao001" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page2" castShadow receiveShadow geometry={nodes.Page2.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.242, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao005" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page3" castShadow receiveShadow geometry={nodes.Page3.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.24, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao007" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page4" castShadow receiveShadow geometry={nodes.Page4.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.238, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao006" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page8" castShadow receiveShadow geometry={nodes.Page8.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.23, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao009" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page7" castShadow receiveShadow geometry={nodes.Page7.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.232, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao008" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page6" castShadow receiveShadow geometry={nodes.Page6.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.234, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao010" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page5" castShadow receiveShadow geometry={nodes.Page5.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.236, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao011" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page13" castShadow receiveShadow geometry={nodes.Page13.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.221, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao012" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page14" castShadow receiveShadow geometry={nodes.Page14.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.219, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao013" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page15" castShadow receiveShadow geometry={nodes.Page15.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.218, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao015" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page16" castShadow receiveShadow geometry={nodes.Page16.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.216, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao014" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page12" castShadow receiveShadow geometry={nodes.Page12.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.223, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao017" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page11" castShadow receiveShadow geometry={nodes.Page11.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.225, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao016" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page10" castShadow receiveShadow geometry={nodes.Page10.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.227, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao018" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page9" castShadow receiveShadow geometry={nodes.Page9.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.229, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao019" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page25" castShadow receiveShadow geometry={nodes.Page25.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.199, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao002" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page26" castShadow receiveShadow geometry={nodes.Page26.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.197, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao003" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page27" castShadow receiveShadow geometry={nodes.Page27.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.195, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao020" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page28" castShadow receiveShadow geometry={nodes.Page28.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.193, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao004" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page32" castShadow receiveShadow geometry={nodes.Page32.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.186, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao022" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page31" castShadow receiveShadow geometry={nodes.Page31.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.188, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao021" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page30" castShadow receiveShadow geometry={nodes.Page30.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.189, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao023" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page29" castShadow receiveShadow geometry={nodes.Page29.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.191, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao024" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page21" castShadow receiveShadow geometry={nodes.Page21.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.206, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao025" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page22" castShadow receiveShadow geometry={nodes.Page22.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.204, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao026" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page23" castShadow receiveShadow geometry={nodes.Page23.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.203, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao028" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page24" castShadow receiveShadow geometry={nodes.Page24.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.201, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao027" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page20" castShadow receiveShadow geometry={nodes.Page20.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.208, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao030" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page19" castShadow receiveShadow geometry={nodes.Page19.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.21, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao029" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page18" castShadow receiveShadow geometry={nodes.Page18.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.212, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao031" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page17" castShadow receiveShadow geometry={nodes.Page17.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.214, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao032" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page49LastFlip" castShadow receiveShadow geometry={nodes.Page49LastFlip.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.154, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao033" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page56" castShadow receiveShadow geometry={nodes.Page56.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.141, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao038" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page55" castShadow receiveShadow geometry={nodes.Page55.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.143, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao037" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page61" castShadow receiveShadow geometry={nodes.Page61.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.131, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao041" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page62" castShadow receiveShadow geometry={nodes.Page62.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.129, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao042" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page63" castShadow receiveShadow geometry={nodes.Page63.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.128, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao044" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page64" castShadow receiveShadow geometry={nodes.Page64.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.126, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao043" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page60" castShadow receiveShadow geometry={nodes.Page60.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.133, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao061" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page59" castShadow receiveShadow geometry={nodes.Page59.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.135, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao045" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page58" castShadow receiveShadow geometry={nodes.Page58.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.137, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao062" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page57" castShadow receiveShadow geometry={nodes.Page57.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.139, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao063" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page41" castShadow receiveShadow geometry={nodes.Page41.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.169, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao046" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page42" castShadow receiveShadow geometry={nodes.Page42.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.167, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao047" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page43" castShadow receiveShadow geometry={nodes.Page43.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.165, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao049" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page44" castShadow receiveShadow geometry={nodes.Page44.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.163, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao048" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page48" castShadow receiveShadow geometry={nodes.Page48.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.156, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao051" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page47" castShadow receiveShadow geometry={nodes.Page47.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.158, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao050" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page46" castShadow receiveShadow geometry={nodes.Page46.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.159, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao052" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page45" castShadow receiveShadow geometry={nodes.Page45.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.161, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao053" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page37" castShadow receiveShadow geometry={nodes.Page37.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.176, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao054" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page38" castShadow receiveShadow geometry={nodes.Page38.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.174, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao055" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page39" castShadow receiveShadow geometry={nodes.Page39.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.173, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao057" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page40" castShadow receiveShadow geometry={nodes.Page40.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.171, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao056" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page36" castShadow receiveShadow geometry={nodes.Page36.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.178, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao059" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page35" castShadow receiveShadow geometry={nodes.Page35.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.18, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao058" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page34" castShadow receiveShadow geometry={nodes.Page34.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.182, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao060" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page33" castShadow receiveShadow geometry={nodes.Page33.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.184, 24.909]} rotation={[3.138, -0.002, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao064" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page65" castShadow receiveShadow geometry={nodes.Page65.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.124, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao065" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page66" castShadow receiveShadow geometry={nodes.Page66.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.122, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao069" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page67" castShadow receiveShadow geometry={nodes.Page67.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.121, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao071" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page68" castShadow receiveShadow geometry={nodes.Page68.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.119, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao070" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page72" castShadow receiveShadow geometry={nodes.Page72.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.111, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao073" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page71" castShadow receiveShadow geometry={nodes.Page71.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.113, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao072" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page70" castShadow receiveShadow geometry={nodes.Page70.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.115, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao074" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page69" castShadow receiveShadow geometry={nodes.Page69.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.117, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao075" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page77" castShadow receiveShadow geometry={nodes.Page77.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.102, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao076" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page78" castShadow receiveShadow geometry={nodes.Page78.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.1, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao077" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page79" castShadow receiveShadow geometry={nodes.Page79.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.098, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao079" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page80" castShadow receiveShadow geometry={nodes.Page80.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.096, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao078" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page76" castShadow receiveShadow geometry={nodes.Page76.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.104, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao081" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page75" castShadow receiveShadow geometry={nodes.Page75.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.106, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao080" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page74" castShadow receiveShadow geometry={nodes.Page74.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.107, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao082" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page73" castShadow receiveShadow geometry={nodes.Page73.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.109, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao083" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page89" castShadow receiveShadow geometry={nodes.Page89.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.08, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao066" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page90" castShadow receiveShadow geometry={nodes.Page90.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.078, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao067" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page91" castShadow receiveShadow geometry={nodes.Page91.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.076, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao084" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page92" castShadow receiveShadow geometry={nodes.Page92.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.074, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao068" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page96" castShadow receiveShadow geometry={nodes.Page96.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.067, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao086" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page95" castShadow receiveShadow geometry={nodes.Page95.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.069, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao085" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page94" castShadow receiveShadow geometry={nodes.Page94.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.07, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao087" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page93" castShadow receiveShadow geometry={nodes.Page93.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.072, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao088" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page85" castShadow receiveShadow geometry={nodes.Page85.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.087, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao089" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page86" castShadow receiveShadow geometry={nodes.Page86.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.085, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao090" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page87" castShadow receiveShadow geometry={nodes.Page87.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.083, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao092" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page88" castShadow receiveShadow geometry={nodes.Page88.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.081, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao091" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page84" castShadow receiveShadow geometry={nodes.Page84.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.089, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao094" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page83" castShadow receiveShadow geometry={nodes.Page83.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.091, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao093" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page82" castShadow receiveShadow geometry={nodes.Page82.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.093, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao095" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page81" castShadow receiveShadow geometry={nodes.Page81.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.094, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao096" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page99" castShadow receiveShadow geometry={nodes.Page99.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.062, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao097" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page98" castShadow receiveShadow geometry={nodes.Page98.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.063, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao102" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page97" castShadow receiveShadow geometry={nodes.Page97.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.065, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao101" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page50" castShadow receiveShadow geometry={nodes.Page50.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.152, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao034" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page51" castShadow receiveShadow geometry={nodes.Page51.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.15, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao036" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page52" castShadow receiveShadow geometry={nodes.Page52.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.148, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao035" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page53" castShadow receiveShadow geometry={nodes.Page53.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.146, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao040" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <mesh name="Page54" castShadow receiveShadow geometry={nodes.Page54.geometry} material={materials.PaletteMaterial002} position={[-20.712, 9.144, 24.909]} rotation={[3.138, -0.006, -3.139]} scale={[0.625, 1.011, 1.029]}>
          <group name="Rotacao039" position={[-0.971, 0.002, -0.057]} rotation={[-1.586, 0.008, 3.102]} scale={[1.6, 0.972, 0.989]} />
        </mesh>
        <group name="Janela">
          <mesh name="Mesh019" castShadow receiveShadow geometry={nodes.Mesh019.geometry} material={materials.MoldeVidroMaterial} />
          <mesh name="Mesh019_1" castShadow receiveShadow geometry={nodes.Mesh019_1.geometry} material={materials.PaletteMaterial012} />
          <mesh name="Wood_W-L" castShadow receiveShadow geometry={nodes['Wood_W-L'].geometry} material={materials.MoldeVidroMaterial} position={[-12.242, 25.541, -26.025]} rotation={[-Math.PI, 0, 0]} />
          <mesh name="Wood_W-R" castShadow receiveShadow geometry={nodes['Wood_W-R'].geometry} material={materials.MoldeVidroMaterial} position={[5.15, 25.711, -26.024]} />
        </group>
        <mesh name="DetalheVitrola" castShadow receiveShadow geometry={nodes.DetalheVitrola.geometry} material={materials.vitrolaWood} position={[-26.42, 9.328, 27.615]} />
        <mesh name="TampaVitrola" castShadow receiveShadow geometry={nodes.TampaVitrola.geometry} material={materials.PaletteMaterial006} position={[-26.558, 10.718, 26.171]} />
        <mesh name="Operating_glass_L" castShadow receiveShadow geometry={nodes.Operating_glass_L.geometry} material={materials.PaletteMaterial011} rotation={[-Math.PI, 0, -Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cena-transformed.glb')
